### ISSUE TITLE
emojipacks fails after the most recent slack update

### ISSUE THREAD

**Issue by 101shipit** [lambtron/emojipacks#158]
Slack has update the web UI for the emojis page, and now emojipacks now fails with the following.
```
Starting import
Got tokens
Logged in
Uh oh! Error: Login error: could not get emoji upload crumb for https://yourteam.slack.com
(node:12714) UnhandledPromiseRejectionWarning: Error: Login error: could not get emoji upload crumb for https://yourteam.slack.com
    at Slack.emoji (/Users/dc/Documents/src/emojipacks/lib/slack.js:162:34)
    at Slack.emoji.next (<anonymous>)
    at onFulfilled (/Users/dc/Documents/src/emojipacks/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:178:7)
(node:12714) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12714) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Ruegen** [comment]
Happens to me too, did they change the Slack api?

**Comment by Ruegen** [comment]
[same error](https://github.com/lambtron/emojipacks/issues/157)

**Comment by kazuuuutaka** [comment]
occur same error

**Comment by SatyrTrickster** [comment]
Same error

**Comment by tsasaki609** [comment]
Same error

**Comment by camwhite** [comment]
In my opinion this module needs to be rewritten using [puppeteer](https://github.com/GoogleChrome/puppeteer) because Slack has added a modal you must click through.

**Comment by itslenny** [comment]
@camwhite On it... Slapped this together in a few hours. It's worked well for me so far.

https://github.com/itslenny/slack-emoji-import

**Comment by camwhite** [comment]
Lol they could only stop bulk uploads for less than a week! Good job @itslenny !!!!

**Comment by jackellenberger** [comment]
@camwhite no need for puppeteer, they actually added emoji uploads to the proper api (albeit undocumented), so all you need is a user token. No client crumb or cookie needed so no need to interact with the browser!

**Comment by jackellenberger** [comment]
@lambtron this can be closed with https://github.com/lambtron/emojipacks/pull/155 !

**Comment by edward-hong** [comment]
Hi I've tried both and get different errors. For `slack-emoji-import` I get the error: 

```
(node:70387) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector ".p-customize_emoji_wrapper .c-button--primary" failed: timeout 30000ms exceeded
```

For `emojipacks` I get the error:

```
Uh oh! Error: Login error: could not get emoji upload crumb for https://url.slack.com
```

**Comment by ghost** [comment]
@jackellenberger it seems emojipacks still doesn't work - i tried cloning straight from your fork too.
```
Uh oh! Error: Application Error: unable to find api token on login page
(node:14149) UnhandledPromiseRejectionWarning: Error: Application Error: unable to find api token on login page
    at Slack.login (/Users/michaelmidura/Development/emojipacks/lib/slack.js:156:13)
    at Slack.login.next (<anonymous>)
    at onFulfilled (/Users/michaelmidura/Development/emojipacks/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14149) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by jackellenberger** [comment]
@michaelwm I can't reproduce, are you sure you're specifying the correct creds? 

I've moved most of my emoji-development time to [emojme](https://github.com/jackellenberger/emojme) which does a few more things than emojipacks, but doesn't come with any packs of its own.

**Comment by rreynier** [comment]
I am seeing the same issue as @michaelwm .  Maybe slack updated the interface again?

**Comment by blineadam** [comment]
simply open the package.js file and modify
  return 'https://' + subdomain + '.slack.com';
to be
  return 'https://' + subdomain + '.slack.com/?no_sso=1';
and re-run make.  This will fix emojipacks.

**Comment by bronek89** [comment]
Hi!
It seems that on npm is version without this fix:
https://www.npmjs.com/package/emojipacks (last release about year ago)

**Comment by gzurbach** [comment]
I confirm that cloning the repo solves the issue. Would be great if the latest was published to `npm` though.

**Comment by itsamayo** [comment]
> @jackellenberger it seems emojipacks still doesn't work - i tried cloning straight from your fork too.
> 
> ```
> Uh oh! Error: Application Error: unable to find api token on login page
> (node:14149) UnhandledPromiseRejectionWarning: Error: Application Error: unable to find api token on login page
>     at Slack.login (/Users/michaelmidura/Development/emojipacks/lib/slack.js:156:13)
>     at Slack.login.next (<anonymous>)
>     at onFulfilled (/Users/michaelmidura/Development/emojipacks/node_modules/co/index.js:65:19)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:14149) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> ```

Also getting this error with correct creds

**Comment by jackellenberger** [comment]
Hey @AshKetchumza, this is actually a different problem then what was happening before; Slack recently updated their pages to not use a long configuration string that was [regex'd into](https://github.com/lambtron/emojipacks/blob/ee731adc217c0c5361fe554937f775c6ba5ee676/lib/slack.js#L27), but as of yesterday they use a nice lil JSON.

That file, /lib/slack.js, will need an update for the login to work again.

**Comment by xlogix** [comment]
+1 Still having this error in 2020

**Comment by davidkhardwick** [comment]
+1 same

**Comment by emeria** [comment]
Anyone find a fix for this?

**Comment by andrewmwilson** [comment]
@emeria: no I didn't find a fix. I ended up just using this
https://chrome.google.com/webstore/detail/neutral-face-emoji-tools/anchoacphlfbdomdlomnbbfhcmcdmjej
