### ISSUE TITLE
Failing after entering email

### ISSUE THREAD

**Issue by nickygencs17** [lambtron/emojipacks#159]
Windows 7
$ npm -version
5.6.0

```
$ emojipacks
Slack subdomain: slack-domain
Email address login: user@email.com
(node:13256) UnhandledPromiseRejectionWarning: TypeError: process.stdin.setRawMode is not a funct                           ion
    at C:\Users\{USER}\AppData\Roaming\npm\node_modules\emojipacks\node_modules\co-prompt\index.js                           :71:19
    at C:\Users\{USER}\AppData\Roaming\npm\node_modules\emojipacks\node_modules\co\index.js:136:8
    at new Promise (<anonymous>)
    at thunkToPromise (C:\Users\{USER}\AppData\Roaming\npm\node_modules\emojipacks\node_modules\co                           \index.js:135:10)
    at toPromise (C:\Users\{USER}\AppData\Roaming\npm\node_modules\emojipacks\node_modules\co\inde                           x.js:119:55)
    at next (C:\Users\{USER}\AppData\Roaming\npm\node_modules\emojipacks\node_modules\co\index.js:                           99:29)
    at onFulfilled (C:\Users\{USER}\AppData\Roaming\npm\node_modules\emojipacks\node_modules\co\in                           dex.js:69:7)
    at C:\Users\{USER}\AppData\Roaming\npm\node_modules\emojipacks\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at co (C:\Users\{USER}\AppData\Roaming\npm\node_modules\emojipacks\node_modules\co\index.js:50                           :10)
(node:13256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated                            either by throwing inside of an async function without a catch block, or by rejecting a promise                            which was not handled with .catch(). (rejection id: 2)
(node:13256) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the fu                           ture, promise rejections that are not handled will terminate the Node.js process with a non-zero                            exit code.

```

**Comment by arukaen** [comment]
Try node6 instead. That seems to work the best for me. If you have docker installed I have a PR where I've added docker support. https://github.com/lambtron/emojipacks/pull/163

**Comment by nickygencs17** [comment]
$ npm -version
6.4.1
Same issue

**Comment by arukaen** [comment]
> $ npm -version
> 6.4.1
> Same issue

Should've mentioned I'm on Linux where-as you are on Windows. Maybe something different there.
