### ISSUE TITLE
Uh oh! Error: Login error: could not get login form for https://workspacename.slack.com

### ISSUE THREAD

**Issue by kamilk91** [lambtron/emojipacks#171]

**Comment by emeria** [comment]
Same issue.

**Comment by hkmaly** [comment]
Same issue.

**Comment by teiling88** [comment]
Same issue!

**Comment by patrick-armitage** [comment]
```
Starting import
Uh oh! Error: Login error: could not get login form for https://**my-domain**.slack.com
/Users/admin/Code/emojipacks/lib/slack.js:101
    if (!opts.formData.signin && !opts.formData.redir && !opts.formData.crumb) throw new Error('Login error: could not get login form for ' + opts.url);
                                                                                     ^

Error: Login error: could not get login form for https://**my-domain**.slack.com
    at Slack.tokens (/Users/admin/Code/emojipacks/lib/slack.js:101:86)
    at Slack.tokens.next (<anonymous>)
    at onFulfilled (/Users/admin/Code/emojipacks/node_modules/co/index.js:65:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.1.0
```
